### ISSUE TITLE
Amazon fallback intent not handled

### ISSUE THREAD

**Issue by PhilCorcoran** [RasaHQ/tutorial-rasa-alexa#4]
An exception occurs when Alexa does not recognize the intent. Then there are no slot values passed to alexa_connector.py. The code should handle AMAZON.FallbackIntent

**Comment by sara-tagger** [comment]
Thanks for the issue, @hsm207 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by PhilCorcoran** [comment]
@hsm207 I have submitted a pull request to fix this

**Comment by hsm207** [comment]
thanks @PhilCorcoran !
